//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBinding.SquadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnimalType", Namespace="http://schemas.datacontract.org/2004/07/Service.DAL")]
    [System.SerializableAttribute()]
    public partial class AnimalType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataBinding.SquadService.Animal[] AnimalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataBinding.SquadService.SQUAD TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataBinding.SquadService.Animal[] Animals {
            get {
                return this.AnimalsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnimalsField, value) != true)) {
                    this.AnimalsField = value;
                    this.RaisePropertyChanged("Animals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataBinding.SquadService.SQUAD Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Animal", Namespace="http://schemas.datacontract.org/2004/07/Practice.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataBinding.SquadService.Insect))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataBinding.SquadService.Butterfly))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataBinding.SquadService.Spider))]
    public partial class Animal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataBinding.SquadService.SQUAD SquadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataBinding.SquadService.SQUAD Squad {
            get {
                return this.SquadField;
            }
            set {
                if ((this.SquadField.Equals(value) != true)) {
                    this.SquadField = value;
                    this.RaisePropertyChanged("Squad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SQUAD", Namespace="http://schemas.datacontract.org/2004/07/Practice.Core")]
    public enum SQUAD : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        spiders = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lepidoptera = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insect", Namespace="http://schemas.datacontract.org/2004/07/Practice.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataBinding.SquadService.Butterfly))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataBinding.SquadService.Spider))]
    public partial class Insect : DataBinding.SquadService.Animal {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FeetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDangerousField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Feet {
            get {
                return this.FeetField;
            }
            set {
                if ((this.FeetField.Equals(value) != true)) {
                    this.FeetField = value;
                    this.RaisePropertyChanged("Feet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDangerous {
            get {
                return this.IsDangerousField;
            }
            set {
                if ((this.IsDangerousField.Equals(value) != true)) {
                    this.IsDangerousField = value;
                    this.RaisePropertyChanged("IsDangerous");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Butterfly", Namespace="http://schemas.datacontract.org/2004/07/Practice.Core")]
    [System.SerializableAttribute()]
    public partial class Butterfly : DataBinding.SquadService.Insect {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WingsAreaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WingsArea {
            get {
                return this.WingsAreaField;
            }
            set {
                if ((this.WingsAreaField.Equals(value) != true)) {
                    this.WingsAreaField = value;
                    this.RaisePropertyChanged("WingsArea");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Spider", Namespace="http://schemas.datacontract.org/2004/07/Practice.Core")]
    [System.SerializableAttribute()]
    public partial class Spider : DataBinding.SquadService.Insect {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasPoisonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRareField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasPoison {
            get {
                return this.HasPoisonField;
            }
            set {
                if ((this.HasPoisonField.Equals(value) != true)) {
                    this.HasPoisonField = value;
                    this.RaisePropertyChanged("HasPoison");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRare {
            get {
                return this.IsRareField;
            }
            set {
                if ((this.IsRareField.Equals(value) != true)) {
                    this.IsRareField = value;
                    this.RaisePropertyChanged("IsRare");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SquadService.SquadService")]
    public interface SquadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquadService/GetByIdFromCache", ReplyAction="http://tempuri.org/SquadService/GetByIdFromCacheResponse")]
        DataBinding.SquadService.AnimalType GetByIdFromCache(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquadService/GetByIdFromCache", ReplyAction="http://tempuri.org/SquadService/GetByIdFromCacheResponse")]
        System.Threading.Tasks.Task<DataBinding.SquadService.AnimalType> GetByIdFromCacheAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquadService/Save", ReplyAction="http://tempuri.org/SquadService/SaveResponse")]
        DataBinding.SquadService.AnimalType Save(DataBinding.SquadService.AnimalType squad, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquadService/Save", ReplyAction="http://tempuri.org/SquadService/SaveResponse")]
        System.Threading.Tasks.Task<DataBinding.SquadService.AnimalType> SaveAsync(DataBinding.SquadService.AnimalType squad, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquadService/Squads", ReplyAction="http://tempuri.org/SquadService/SquadsResponse")]
        DataBinding.SquadService.AnimalType[] Squads();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SquadService/Squads", ReplyAction="http://tempuri.org/SquadService/SquadsResponse")]
        System.Threading.Tasks.Task<DataBinding.SquadService.AnimalType[]> SquadsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SquadServiceChannel : DataBinding.SquadService.SquadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SquadServiceClient : System.ServiceModel.ClientBase<DataBinding.SquadService.SquadService>, DataBinding.SquadService.SquadService {
        
        public SquadServiceClient() {
        }
        
        public SquadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SquadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SquadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SquadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataBinding.SquadService.AnimalType GetByIdFromCache(int id) {
            return base.Channel.GetByIdFromCache(id);
        }
        
        public System.Threading.Tasks.Task<DataBinding.SquadService.AnimalType> GetByIdFromCacheAsync(int id) {
            return base.Channel.GetByIdFromCacheAsync(id);
        }
        
        public DataBinding.SquadService.AnimalType Save(DataBinding.SquadService.AnimalType squad, int id) {
            return base.Channel.Save(squad, id);
        }
        
        public System.Threading.Tasks.Task<DataBinding.SquadService.AnimalType> SaveAsync(DataBinding.SquadService.AnimalType squad, int id) {
            return base.Channel.SaveAsync(squad, id);
        }
        
        public DataBinding.SquadService.AnimalType[] Squads() {
            return base.Channel.Squads();
        }
        
        public System.Threading.Tasks.Task<DataBinding.SquadService.AnimalType[]> SquadsAsync() {
            return base.Channel.SquadsAsync();
        }
    }
}
